# ASCEND基础示例配置文件
ascend:
  version: "1.0.0"
  framework: "ascend"
# 插件配置（支持版本约束）


# 插件路径配置
plugin_paths:
  - "C:\\Users\\viare\\vscodeproject\\ASCEND\\ascend\\agent_plugins" # 相对于项目根目录的插件目录
plugins:
  - "rl_sb3" # Stable-Baselines3 强化学习插件
rl_sb3:
  algorithm: "ppo" # 使用PPO算法
  policy: "MlpPolicy" # 使用多层感知机策略
  learning_rate: 0.0003
  batch_size: 64
  n_steps: 2048
  device: "auto"
  verbose: 1
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  clip_range: 0.2
