# ASCEND基础示例配置文件
ascend:
  version: "1.0.0"
  framework: "ascend"
# 插件配置（支持版本约束）


# 插件路径配置
plugin_paths:
  - "./plugins" # 相对路径插件目录
  - "${HOME}/.ascend/plugins" # 用户级插件目录
  - "/opt/ascend/plugins" # 系统级插件目录
plugins:
  - "ascend_rl_sb3" # Tushare数据插件
# Tushare数据插件配置
ascend_rl_sb3:
  algorithm: "ppo" # 使用PPO算法
  policy: "MlpPolicy" # 使用多层感知机策略
  learning_rate: 0.0003
  batch_size: 64
  n_steps: 2048
  device: "auto"
  verbose: 1
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  clip_range: 0.2
